# This pod complies with all Kyverno policies
apiVersion: v1
kind: Pod
metadata:
  name: test-compliant-pod
  namespace: default
  labels:
    app: test
    version: "1.0"
spec:
  containers:
  - name: test
    image: nginx:latest
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      privileged: false
      capabilities:
        drop:
        - ALL
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"

