apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-role
  namespace: default
  labels:
    app: postgres
rules:
# Allow reading own ConfigMap and Secret
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  resourceNames: ["postgres-init-scripts", "postgres-secret"]
  verbs: ["get", "list"]
# Allow reading persistent volume claims
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  resourceNames: ["postgres-pvc"]
  verbs: ["get"]

