apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-directory
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      exclude: '{*.sh,README.md}'
      include: '*.yaml'
      recurse: true
    path: general_info/projects/Project_Portal/k8s
    repoURL: https://github.com/daasnigeria/daascohort3.git
    targetRevision: main
