---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: government-api-sa
  namespace: pod-security
  labels:
    app: government-api
    component: serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: government-api-role
  namespace: pod-security
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    resourceNames: ["government-api-config", "government-api-secret"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: government-api-binding
  namespace: pod-security
subjects:
- kind: ServiceAccount
  name: government-api-sa
  namespace: pod-security
roleRef:
  kind: Role
  name: government-api-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: government-api
  namespace: pod-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: government-api
  template:
    metadata:
      labels:
        app: government-api
    spec:
      # Pod-level security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: government-api-sa
      containers:
      - name: government-api
        image: daasnigeria/daasrepo:government-api
        imagePullPolicy: Always
        # Container-level security context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
        ports:
        - containerPort: 8081
          name: http
        envFrom:
        - configMapRef:
            name: government-api-config
        - secretRef:
            name: government-api-secret
        # Volume for writable directories (if needed)
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: var-run
          mountPath: /var/run
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: tmp
        emptyDir: {}
      - name: var-run
        emptyDir: {}

