
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loan-validator-portal-sa
  namespace: pod-security
  labels:
    app: loan-validator-portal
    component: serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loan-validator-portal-role
  namespace: pod-security
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    resourceNames: ["loan-validator-portal-config", "loan-validator-portal-secret"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loan-validator-portal-binding
  namespace: pod-security
subjects:
  - kind: ServiceAccount
    name: loan-validator-portal-sa
    namespace: pod-security
roleRef:
  kind: Role
  name: loan-validator-portal-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-validator-portal
  namespace: pod-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-validator-portal
  template:
    metadata:
      labels:
        app: loan-validator-portal
    spec:
      # Pod-level security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: loan-validator-portal-sa
      containers:
      - name: loan-validator-portal
        image: daasnigeria/daasrepo:loan-validator-portal
        imagePullPolicy: Always
        # Container-level security context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: loan-validator-portal-config
        - secretRef:
            name: loan-validator-portal-secret
        # Volume for writable directories (if needed)
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: var-run
          mountPath: /var/run
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "400m"
      volumes:
      - name: tmp
        emptyDir: {}
      - name: var-run
        emptyDir: {}

